<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Jan Dvorak</Authors>
    <PackageProjectUrl>https://github.com/jdvor/easy-timeseries</PackageProjectUrl>
    <RepositoryUrl>https://github.com/jdvor/easy-timeseries</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

</Project>
