<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Easy.TimeSeries.AzureBlobs\Easy.TimeSeries.AzureBlobs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MartinCostello.Logging.XUnit.v3" />
    <PackageReference Include="Testcontainers.Azurite" />
  </ItemGroup>
</Project>
