namespace Easy.TimeSeries.SrcGen.Emit;

using Easy.TimeSeries.SrcGen.Model;
using Microsoft.CodeAnalysis.CSharp;

internal readonly record struct GeneratedSource(string HintName, string Code);

internal static class EmitterCommon
{
    public static readonly string GeneratorVersion =
        typeof(EmitterCommon).Assembly.GetName().Version?.ToString() ?? "1.0.0.0";

    public const string AbstractionsNs = "global::Easy.TimeSeries.Abstractions";
    public const string CoreNs = "global::Easy.TimeSeries";

    public static string HintName(TargetTypeModel model, string suffix)
        => model.Namespace is null ? $"{model.TypeName}{suffix}.g.cs" : $"{model.Namespace}.{model.TypeName}{suffix}.g.cs";

    /// <summary>Emits the file preamble up to and including the namespace declaration.</summary>
    public static CodeBuilder StartFile(TargetTypeModel model)
    {
        var code = new CodeBuilder()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line();

        if (model.Namespace is not null)
        {
            code.Line($"namespace {model.Namespace};").Line();
        }

        return code;
    }

    public static CodeBuilder GeneratedCodeAttribute(this CodeBuilder code)
        => code.Line($"[global::System.CodeDom.Compiler.GeneratedCode(\"Easy.TimeSeries.SrcGen\", \"{GeneratorVersion}\")]");

    /// <summary>C# string literal (quoted and escaped) for the given text.</summary>
    public static string Literal(string text) => SymbolDisplay.FormatLiteral(text, quote: true);

    /// <summary>The CLR type of the column's values, as emitted source text.</summary>
    public static string ClrType(ColumnKind kind)
        => kind switch
        {
            ColumnKind.Category => "string",
            ColumnKind.Int32 => "int",
            ColumnKind.Int64 => "long",
            ColumnKind.Float or ColumnKind.ScaledNumber32 => "float",
            ColumnKind.Double or ColumnKind.ScaledNumber64 => "double",
            ColumnKind.Decimal => "decimal",
            ColumnKind.Bool => "bool",
            ColumnKind.DateTimeOrdered or ColumnKind.DateTimeUnordered => "global::System.DateTime",
            ColumnKind.TimeSpan => "global::System.TimeSpan",
            _ => throw new InvalidOperationException($"No CLR type for column kind {kind}."),
        };
}
