[book]
title = "Easy TimeSeries"
description = "..."
language = "en"
src = "."

[build]
build-dir = "../site"

# https://gitlab.com/tglman/mdbook-variables
[preprocessor.variables]
use_env = false

[preprocessor.variables.variables]
author_name = "Jan Dvořák"
author_email = "github.mandarin334@passmail.com"
copyright = "Copyright (c) 2026 Jan Dvořák"

# https://github.com/badboy/mdbook-mermaid
[preprocessor.mermaid]
command = "mdbook-mermaid"

# https://github.com/badboy/mdbook-toc
[preprocessor.toc]
command = "mdbook-toc"
max-level = 3
renderer = ["html"]

[output.html]
additional-js = ["./assets/vendor/mermaid.min.js", "./assets/vendor/mermaid-init.js"]
additional-css = ["./assets/vendor/mdbook-admonish.css"]

[output.html.print]
enable = false

[output.html.fold]
enable = true
