<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Easy.TimeSeries.Abstractions\Easy.TimeSeries.Abstractions.csproj" />
    <ProjectReference Include="..\Easy.TimeSeries\Easy.TimeSeries.csproj" />
    <ProjectReference Include="..\Easy.TimeSeries.SrcGen\Easy.TimeSeries.SrcGen.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
